### PR TITLE
Refactor bot.rb

### PR DESCRIPTION
**Pull request by romulomachado**
- Get rid of too many if's, else's and unless's

### CODE REVIEW

**Comment by lfcipriani** [comment]
Thanks Romulo, I'll integrate that soon

**Comment by lfcipriani** [comment]
sorry for taking too long

**Comment by romulomachado** [comment]
:+1:

**Comment by lfcipriani** [comment]
Romulo, your commit erased the code needed to execute the request. Unfortunately, I merged without check that, can you fix this problem?

**Comment by romulomachado** [comment]
Oh, I'm sorry! I'll fix it.

**Comment by romulomachado** [comment]
ping @lfcipriani

**Pull request merged**
